### ISSUE TITLE
Add decoder feature inside std package

### ISSUE THREAD

**Issue by peter279k** [brick/std#7]
It's about issue #6, I think we can implement `URL decode`, `base64 decode`, `base32 decode`, `base 58 decode` and etc.

**Comment by BenMorel** [comment]
Sorry, I don't want to add more stuff to this library at the moment. I'm not really sure how I want it to evolve, I may split it into several independent repos at some point.

**Comment by peter279k** [comment]
Hi @BenMorel, thank you for your explanation.

If you create another package about that, please let me know.

Thanks :).
